FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements.txt /app/backend/requirements.txt
RUN pip install --no-cache-dir -r /app/backend/requirements.txt
RUN pip install --no-cache-dir aiogram==3.17.0

COPY backend /app/backend
COPY bot /app/bot

ENV PYTHONPATH=/app

CMD ["python", "-m", "bot.main"]
