from __future__ import annotations

CREATING_PAYMENT_ATTEMPT_STATUS = "creating"
RETRY_REQUIRED_PAYMENT_ATTEMPT_STATUS = "retry_required"
REVIEW_REQUIRED_PAYMENT_ATTEMPT_STATUS = "review_required"
COMPLETED_PAYMENT_ATTEMPT_STATUS = "completed"
ABANDONED_PAYMENT_ATTEMPT_STATUS = "abandoned"

OPEN_PAYMENT_ATTEMPT_STATUSES = frozenset(
    {
        CREATING_PAYMENT_ATTEMPT_STATUS,
        RETRY_REQUIRED_PAYMENT_ATTEMPT_STATUS,
        REVIEW_REQUIRED_PAYMENT_ATTEMPT_STATUS,
    }
)
RETRYABLE_PAYMENT_ATTEMPT_STATUSES = frozenset(
    {
        CREATING_PAYMENT_ATTEMPT_STATUS,
        RETRY_REQUIRED_PAYMENT_ATTEMPT_STATUS,
    }
)
VALID_PAYMENT_ATTEMPT_STATUSES = frozenset(
    {
        *OPEN_PAYMENT_ATTEMPT_STATUSES,
        COMPLETED_PAYMENT_ATTEMPT_STATUS,
        ABANDONED_PAYMENT_ATTEMPT_STATUS,
    }
)
ERROR_PAYMENT_ATTEMPT_STATUSES = frozenset(
    {
        RETRY_REQUIRED_PAYMENT_ATTEMPT_STATUS,
        REVIEW_REQUIRED_PAYMENT_ATTEMPT_STATUS,
        ABANDONED_PAYMENT_ATTEMPT_STATUS,
    }
)
