from __future__ import annotations

CREATING_PAYMENT_ATTEMPT_STATUS = "creating"
RETRY_REQUIRED_PAYMENT_ATTEMPT_STATUS = "retry_required"
REVIEW_REQUIRED_PAYMENT_ATTEMPT_STATUS = "review_required"
COMPLETED_PAYMENT_ATTEMPT_STATUS = "completed"

RETRYABLE_PAYMENT_ATTEMPT_STATUSES = frozenset(
    {
        CREATING_PAYMENT_ATTEMPT_STATUS,
        RETRY_REQUIRED_PAYMENT_ATTEMPT_STATUS,
    }
)
VALID_PAYMENT_ATTEMPT_STATUSES = frozenset(
    {
        *RETRYABLE_PAYMENT_ATTEMPT_STATUSES,
        REVIEW_REQUIRED_PAYMENT_ATTEMPT_STATUS,
        COMPLETED_PAYMENT_ATTEMPT_STATUS,
    }
)
ERROR_PAYMENT_ATTEMPT_STATUSES = frozenset(
    {
        RETRY_REQUIRED_PAYMENT_ATTEMPT_STATUS,
        REVIEW_REQUIRED_PAYMENT_ATTEMPT_STATUS,
    }
)


def sql_values(values: frozenset[str]) -> str:
    return ", ".join(f"'{value}'" for value in sorted(values))


VALID_PAYMENT_ATTEMPT_STATUS_SQL = sql_values(VALID_PAYMENT_ATTEMPT_STATUSES)
ERROR_PAYMENT_ATTEMPT_STATUS_SQL = sql_values(ERROR_PAYMENT_ATTEMPT_STATUSES)
