from __future__ import annotations

PENDING_PROVIDER_PAYMENT_STATUS = "pending"
WAITING_FOR_CAPTURE_PROVIDER_PAYMENT_STATUS = "waiting_for_capture"
SUCCEEDED_PROVIDER_PAYMENT_STATUS = "succeeded"
CANCELED_PROVIDER_PAYMENT_STATUS = "canceled"

PROVIDER_PAYMENT_STATUSES = frozenset(
    {
        PENDING_PROVIDER_PAYMENT_STATUS,
        WAITING_FOR_CAPTURE_PROVIDER_PAYMENT_STATUS,
        SUCCEEDED_PROVIDER_PAYMENT_STATUS,
        CANCELED_PROVIDER_PAYMENT_STATUS,
    }
)
REUSABLE_PROVIDER_PAYMENT_STATUSES = frozenset(
    {
        PENDING_PROVIDER_PAYMENT_STATUS,
        WAITING_FOR_CAPTURE_PROVIDER_PAYMENT_STATUS,
        SUCCEEDED_PROVIDER_PAYMENT_STATUS,
    }
)
REFUNDABLE_PROVIDER_PAYMENT_STATUSES = frozenset({SUCCEEDED_PROVIDER_PAYMENT_STATUS})


def sql_values(values: frozenset[str]) -> str:
    return ", ".join(f"'{value}'" for value in sorted(values))


PROVIDER_PAYMENT_STATUS_SQL = sql_values(PROVIDER_PAYMENT_STATUSES)
