from __future__ import annotations

REQUESTED_RETURN_STATUS = "requested"
PROCESSING_RETURN_STATUS = "processing"
RETRY_REQUIRED_RETURN_STATUS = "refund_retry_required"
REVIEW_REQUIRED_RETURN_STATUS = "refund_review_required"
PENDING_RETURN_STATUS = "refund_pending"
APPROVED_RETURN_STATUS = "approved"
APPROVED_PARTIAL_RETURN_STATUS = "approved_partial"
FAILED_RETURN_STATUS = "failed"

OPEN_RETURN_STATUSES = frozenset(
    {
        REQUESTED_RETURN_STATUS,
        PROCESSING_RETURN_STATUS,
        RETRY_REQUIRED_RETURN_STATUS,
        REVIEW_REQUIRED_RETURN_STATUS,
        PENDING_RETURN_STATUS,
    }
)
FINAL_RETURN_STATUSES = frozenset(
    {
        APPROVED_RETURN_STATUS,
        APPROVED_PARTIAL_RETURN_STATUS,
    }
)
PROVIDER_LINKED_RETURN_STATUSES = frozenset(
    {
        PENDING_RETURN_STATUS,
        *FINAL_RETURN_STATUSES,
    }
)
AMOUNT_REQUIRED_RETURN_STATUSES = frozenset(
    {
        PROCESSING_RETURN_STATUS,
        RETRY_REQUIRED_RETURN_STATUS,
        REVIEW_REQUIRED_RETURN_STATUS,
        *PROVIDER_LINKED_RETURN_STATUSES,
    }
)
VALID_RETURN_STATUSES = frozenset(
    {
        *OPEN_RETURN_STATUSES,
        *FINAL_RETURN_STATUSES,
        FAILED_RETURN_STATUS,
    }
)


def sql_values(values: frozenset[str]) -> str:
    return ", ".join(f"'{value}'" for value in sorted(values))


OPEN_RETURN_STATUS_SQL = sql_values(OPEN_RETURN_STATUSES)
FINAL_RETURN_STATUS_SQL = sql_values(FINAL_RETURN_STATUSES)
PROVIDER_LINKED_RETURN_STATUS_SQL = sql_values(PROVIDER_LINKED_RETURN_STATUSES)
AMOUNT_REQUIRED_RETURN_STATUS_SQL = sql_values(AMOUNT_REQUIRED_RETURN_STATUSES)
VALID_RETURN_STATUS_SQL = sql_values(VALID_RETURN_STATUSES)
