global:
  resolve_timeout: 5m

route:
  receiver: local-null
  group_by:
    - alertname
    - severity
    - component
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: local-null
